switch_properties = "switch_properties.json"
data_cleaning = "data_cleaning"
log_path = "log_path"
dataset_path = "dataset_path"
credit_assessment = "credit_assessment"
selected_columns = "selected_columns"
target_column = "target_column"